# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ROS2_docs',
                'doc_host': 'https://bthek1.github.io',
                'git_url': 'https://github.com/bthek1/ROS2_docs',
                'lib_path': 'ROS2_docs'},
  'syms': {}}
